#!/bin/bash
# William DURAND <william.durand1@gmail.com>

# Get the files that will be committed
files=`git diff --cached --name-status | awk '$1 != "R" { print $2 }'`

echo '[pre-commit] Fixing permissions and cleaning the code.'

for f in $files ; do
    if [ -f $f ] ; then
        # Fix permissions
        chmod 644 $f
        # Remove trailing whitespaces
        sed -i 's/[[:space:]]*$//' "$f"
        # Remove ^M
        sed -i -e '//d' "$f"

        # Re-add the file to the git index
        git add $f
    fi
done
