# Functions Autoloading
fpath=(~/.zsh $fpath)

# Prompt
autoload -U promptinit && promptinit
prompt pure
# See: https://github.com/sindresorhus/pure/wiki/Customizations,-hacks-and-tweaks#show-number-of-jobs-in-prompt
PROMPT='%(1j.[%j] .)%(?.%F{magenta}.%F{red})${PURE_PROMPT_SYMBOL:-❯}%f '

autoload -Uz compinit
if [ $(date +'%j') != $(stat -f '%Sm' -t '%j' ${ZDOTDIR:-$HOME}/.zcompdump) ]; then
  compinit
else
  compinit -C
fi

# Common ENV variables
export EDITOR='vim'
export GIT_EDITOR='vim'
export SHELL='/bin/zsh'

# Fix Locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# History
export HISTSIZE=100000
export HISTFILE="$HOME/.history"
export SAVEHIST="$HISTSIZE"

# Remove superfluous blanks from each command line being added to the history
# list
setopt histreduceblanks
# Remove command lines from the history list when the first character on the
# line is a space, or when one of the expanded aliases contains a leading space
setopt histignorespace
# Do not enter command lines into the history list if they are duplicates of the
# previous event.
setopt histignorealldups
# Switching directories for lazy people
setopt autocd
# See: http://zsh.sourceforge.net/Intro/intro_6.html
setopt autopushd pushdminus pushdsilent pushdtohome pushdignoredups
# Don't kill background jobs when I logout
setopt nohup
# See: http://zsh.sourceforge.net/Intro/intro_2.html
setopt extendedglob
# Do not require a leading '.' in a filename to be matched explicitly
setopt globdots
# Use vi key bindings in ZSH
setopt vi
# Causes field splitting to be performed on unquoted parameter expansions
setopt shwordsplit
# Automatically use menu completion after the second consecutive request for
# completion
setopt automenu
# If the argument to a cd command (or an implied cd with the AUTO_CD option set)
# is not a directory, and does not begin with a slash, try to expand the
# expression as if it were preceded by a '~'
setopt cdablevars
# Try to make the completion list smaller (occupying less lines) by printing
# the matches in columns with different widths
setopt listpacked
# Don't show types in completion lists
setopt nolisttypes
# If a completion is performed with the cursor within a word, and a full
# completion is inserted, the cursor is moved to the end of the word
setopt alwaystoend
# Try to correct the spelling of commands
setopt correct

# case-insensitive (uppercase from lowercase) completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# process completion
zstyle ':completion:*:processes' command 'ps -au$USER'
zstyle ':completion:*:*:kill:*:processes' list-colors "=(#b) #([0-9]#)*=36=31"

# zstyle
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' menu select=2
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*' ignored-patterns 'package-lock.json'
zstyle ':completion:*:descriptions' format '%U%F{yellow}%d%f%u'
zstyle ':completion:*:*:git:*' script ~/.git-completion.bash

# Reverse search
bindkey -e

# Pager, thanks François <3
if [[ -x `which less` ]] ; then
  export PAGER="less"
  export LESS="--ignore-case --LONG-PROMPT --QUIET --chop-long-lines -Sm --RAW-CONTROL-CHARS --quit-if-one-screen --no-init"

  #http://nion.modprobe.de/blog/archives/572-less-colors-for-man-pages.html
  export LESS_TERMCAP_mb=$'\E[01;31m'
  export LESS_TERMCAP_md=$'\E[01;31m'
  export LESS_TERMCAP_me=$'\E[0m'
  export LESS_TERMCAP_se=$'\E[0m'
  export LESS_TERMCAP_so=$'\E[01;44;33m'
  export LESS_TERMCAP_ue=$'\E[0m'
  export LESS_TERMCAP_us=$'\E[00;32m'
  export MANPAGES='/bin/less'
fi

# alias
alias ls='ls -hFG'
alias ll='ls -lAhFG'
alias dstat='dstat -dcgilmsy'
alias projects="cd ~/projects/"

# convenient aliases
alias diff=icdiff

# git + hub
eval "$(/usr/local/bin/hub alias -s)"

# vi -> vim
alias vi='vim'

# cat -> bat
export BAT_STYLE='changes'
alias cat='bat'

# hit C-X C-E to open your $EDITOR with the command typed in the buffer
# and quickly edit your error
autoload edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line

# fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden'

# Common PATH
export PATH="/usr/local/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/X11/bin:/Developer/usr/bin"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# Homebrew
export HOMEBREW_NO_ANALYTICS=1
export PATH="/usr/local/sbin:$PATH"

# Node
export PATH="$PATH:./node_modules/.bin"
export PATH="$PATH:$(yarn global bin)"

# Ruby, lazy load rbenv because I do not use it too often
rbenv() {
  eval "$(command rbenv init -)"
  rbenv "$@"
}

# PHP
if [[ -d "$HOME/.phpenv" ]]; then
  export PATH="$PATH:$HOME/.phpenv/bin:$HOME/.composer/vendor/bin"

  # lazy load phpenv because I do not use it too often
  phpenv() {
    eval "$(command phpenv init -)"
    phpenv "$@"
  }
fi

# Added by the Heroku Toolbelt
if [[ -d "/usr/local/heroku" ]]; then
  export PATH="$PATH:/usr/local/heroku/bin"
  # heroku autocomplete setup
  HEROKU_AC_ZSH_SETUP_PATH=~/Library/Caches/heroku/autocomplete/zsh_setup && test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH
fi

# Go
if [[ -d "$HOME/projects/go" ]]; then
  export GOPATH="$HOME/projects/go"
  export PATH="$PATH:/usr/local/opt/go/libexec/bin:$GOPATH/bin"
fi

# rust
if [[ -d "$HOME/.cargo" ]]; then
  source $HOME/.cargo/env
fi

# sensitive env vars
if [[ -f ~/.sensitive.sh ]]; then
  source ~/.sensitive.sh
fi

# local zshrc
if [[ -f ~/.zshrc.local ]]; then
  source ~/.zshrc.local
fi
